In [2]:
from IPython.core import debugger as pdb

In [9]:
import pandas as pd
from pandas import *
import time
from collections import defaultdict
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import Imputer

print 'before read csv', time.time()
_df = pd.read_csv('data/train.csv')

print 'after read csv', time.time()
#print df.dtypes
#col_count = open('col_count.txt', 'w+')
#row_count = open('row_count.txt', 'w+')
col_null = _df.shape[0] - _df.count() #显示每列的空null个数
#print >> row_count, df.shape[1] - df.count(axis=1) #显示每行的空null个数
print _df.shape[0], _df.shape[1]
#filtered df
#df = DataFrame() 
#col_cnt = open('col_count_v2.txt', 'w+')
'''for i in range(len(_df.columns)):
    if _df.shape[0] >= 2*col_null[i]:
        if _df[_df.columns[i]].dtype == object:
            dic = defaultdict(int)
            dic2 = defaultdict(int)
            cnt = 1
            for k in range(1, len(_df[_df.columns[i]])):
                if _df[_df.columns[i]][k] is not np.nan:
                    dic[_df[_df.columns[i]][k]] += 1
                    if dic[_df[_df.columns[i]][k]] == 1:
                        dic2[_df[_df.columns[i]][k]] = cnt; cnt += 1
                else:
                    dic[''] += 1
            
            max_val = 0; max_key = ''
            for key in dic:
                if max_val < dic[key]:
                    max_val = dic[key]; max_key = key
            
            print 'why??'
            data2 = _df[[_df.columns[i]]]
            data2 = fill_missing_numeric(data2, _df.columns[i], dic2, max_key)
            df[_df.columns[i]] = data2[_df.columns[i]]
            
        else: 
            df[[_df.columns[i]]] = _df[[_df.columns[i]]]
            #del df[[df.columns[i]]]
    else:
        pass #print df.columns[i]'''



'''new_data = open('data_type.txt', 'w+')
for ele in df.columns:
    print >> new_data, ele, type(ele)'''

'''for attri in df.columns:
    if df[attri].dtype == 'object':
        df[attri] = df[attri].astype('category')'''
        


before read csv 1541799239.82
after read csv 1541799248.37
182190 481


"for attri in df.columns:\n    if df[attri].dtype == 'object':\n        df[attri] = df[attri].astype('category')"

In [10]:
df_drop = _df.dropna(axis=1, thresh=_df.shape[0]//2)
df_drop_all = df_drop.dropna(axis=0, how='any')

print df_drop_all.shape[1]

418


In [11]:
print df_drop_all.shape[0]

14962


In [27]:
for attri in df_drop_all.columns:
    #print type(attri)
    if type(attri) == str:
        labels, unique = pd.factorize(df_drop_all[attri])
        #print labels
        df_drop_all[attri] = labels

[0 0 1 ... 8 2 1]
[ 0  1  2 ... 16 92 23]
[0 1 2 ... 0 2 2]
[0 1 2 ... 9 3 1]
[   0    1    2 ... 4058 4712 4830]


/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[  0   1   2 ... 458 348 130]
[0 0 0 ... 0 0 0]
[0 0 1 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 1 ... 0 0 0]
[0 1 2 ... 6 0 5]
[ 0  1  2 ... 21  0 44]
[ 0  1  2 ... 21 34 32]
[0 0 0 ... 0 0 0]
[0 0 1 ... 0 1 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 3 0]
[0 0 1 ... 4 1 2]
[0 0 1 ... 0 1 1]
[0 1 0 ... 3 0 1]
[0 1 2 ... 3 6 6]
[0 0 0 ... 0 0 1]
[0 0 0 ... 0 0 0]
[ 0  1  2 ... 10  0  8]
[ 0  1  2 ... 28 21  6]
[ 0  1  2 ...  5 24 31]
[0 1 2 ... 5 4 5]
[ 0  1  2 ... 18  1  6]
[0 1 1 ... 2 0 2]
[0 0 0 ... 0 0 0]
[0 0 1 ... 0 0 0]
[0 0 1 ... 0 0 0]
[0 1 0 ... 8 0 7]
[0 1 2 ... 1 2 3]
[0 0 0 ... 0 0 0]
[0 1 1 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 1 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 1 ... 0 0 0]
[0 0 1 ... 0 0 0]
[0 0 1 ... 0 0 0]
[0 0 1 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 1 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 1 0 ... 0 0 0]
[0 0 0 ... 0 0 0

[ 0  0  1 ... 15  6  5]
[ 0  0  1 ... 17 60  5]
[ 0  0  1 ... 18 64  5]
[0 1 2 ... 6 2 6]
[0 1 2 ... 5 2 5]
[ 0  0  1 ... 13  3  2]
[0 0 0 ... 0 0 0]
[ 0  0  1 ... 17 43  2]
[0 0 0 ... 0 0 0]
[0 1 2 ... 4 4 0]
[  0   1   2 ... 189 138 149]
[ 0  1  0 ... 17 11 11]
[ 0  1  2 ...  2  7 12]
[0 1 2 ... 1 1 4]
[ 0  1  2 ... 44 74 17]
[ 0  1  2 ... 18 44  7]
[ 0  1  2 ...  6 50 21]
[0 1 2 ... 2 5 5]
[0 1 2 ... 0 0 0]
[ 0  1  2 ... 32 18  2]
[ 0  1  2 ...  7 28 48]
[ 0  1  2 ...  4  5 17]
[   0    1    2 ... 2257 2558 1269]
[    0     1     2 ... 14959 14960 14961]
[0 0 0 ... 0 0 0]
[0 0 0 ... 1 0 1]
[0 0 0 ... 0 0 0]
[0 1 2 ... 1 2 1]
[0 1 2 ... 2 2 2]
[0 0 1 ... 0 0 0]
[0 0 1 ... 0 0 0]
[0 0 1 ... 0 0 0]
[ 0  1  2 ...  8 18  5]
[0 0 1 ... 3 0 2]


In [46]:
m = df_drop_all.shape[0] # row
n = df_drop_all.shape[1] # col

train_data = df_drop_all[df_drop_all.columns[:-1]]
train_label = df_drop_all[df_drop_all.columns[-1]]
print train_data.shape

print train_label.shape
print train_data.shape[0], train_data.shape[1]
print df_drop_all.columns

(14962, 417)
(14962,)
14962 417
Index([u'date', u'source', u'title', u'state', u'zip', u'mailcode',
       u'has_chapter', u'dob', u'noexch', u'recinhse',
       ...
       u'responded', u'hphone_d', u'rfa_2r', u'rfa_2f', u'rfa_2a', u'mdmaud_r',
       u'mdmaud_f', u'mdmaud_a', u'cluster2', u'geocode2'],
      dtype='object', length=418)


In [48]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.cluster import KMeans
random_state = 170
#clf = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0).fit(np.array(train_data), np.array(train_label))
y = KMeans(n_clusters=2, random_state=random_state).fit_predict(df_drop_all)


In [45]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import ShuffleSplit

cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
scores = cross_val_score(clf, train_data, train_label, cv = cv)
print scores

[0.88573338 0.72836619 0.80554627 0.74072837 0.83294353]


In [ ]:
from sklearn.preprocessing import LabelEncoder

m = df.shape[0] # row
n = df.shape[1] # col
print 'row:', m, 'col:', n

for attri in df.columns:
    if df[attri].dtype == object:
        print 'encode'
        class_le = LabelEncoder()   
        df[attri] = class_le.fit_transform(df[attri].values)
    else:
        print 'numerical'
        for i in range(len(df[attri])):
            if np.isnan(df[attri][i]):
                #data2[attri][i] = round(data2.median()[attri], 3)
                df[attri][i] = df.median()[attri]

    
'''#print 'new', new_df.dtypes
for attri in df.columns:
    if df[attri].dtype == 'category':
        #print '6666666666'
        #df[attri] = df[attri].astype('category')
        imputer = Imputer(missing_values = 'NaN', strategy = 'most_frequent', axis = 0, copy = True)
        imputer = imputer.fit(df[[attri]])
        df[[attri]] = imputer.transform(df[[attri]])
    else:
        imputer = Imputer(missing_values = 'NaN', strategy = 'median', axis = 0, copy = True)
        imputer = imputer.fit(df[[attri]])
        df[[attri]] = imputer.transform(df[[attri]])'''
        
new_col_count = open('new_col_count.txt', 'w+')
#row_count = open('row_count.txt', 'w+')
new_null_cnt = df.shape[0] - df.count() #显示每列的空null个数
for i in range(len(df.columns)):
    print >> new_col_count, df.columns[i], new_null_cnt[i]



print 'after statistic', time.time()

#显示每列有多少种类型的值，每种出现多少次
'''value_cnt = open('value_cnt.txt', 'w+')
for lei in df.columns:
    print >> value_cnt, df[lei].value_counts()'''


train_data = df[:m-1]
train_label = df[m-1:m]
print train_data.shape[0], train_data.shape[1]
print train_label.shape[0]

#clf = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=0).fit(train_data, train_label)



In [ ]:
print 'fuck!!!'